### ISSUE TITLE
“撕”的滑稽头是又默认无法改变的吗

### ISSUE THREAD

**Issue by Danwk2333** [noneplugin/nonebot-plugin-petpet#101]
![2138543729-1142682500-B04FD22D80A4CA52A7F34ECA5D1A82E0](https://user-images.githubusercontent.com/106854600/181783356-a07885a9-b92c-40ba-a907-dea3ae1fa54e.jpg)

**Comment by MeetWq** [comment]
个人认为把滑稽换成头像比较奇怪

**Comment by Danwk2333** [comment]
能考虑两种模式都存在吗

**Comment by MeetWq** [comment]
改成了指定两个目标时，用第一个目标的头像替换滑稽头
