### ISSUE TITLE
求助：调用插件时出现报错

### ISSUE THREAD

**Issue by shmilyty** [noneplugin/nonebot-plugin-petpet#109]
我在安装时把 resource 里所有东西都复制到了 data 文件夹里，但是在实际调用时有一些会报错，下图是我在私聊里调用 `远离` 的报错：

![image](https://user-images.githubusercontent.com/61276699/184125704-5e5f2fbd-f285-44c5-9e83-22b7c5a1a4f6.png)

![image](https://user-images.githubusercontent.com/61276699/184126021-816ad78c-a97e-45b4-8826-885484576323.png)

求助一下是我哪里配置的时候出现了问题/wq

**Comment by MeetWq** [comment]
按照 [nonebot-plugin-imageutils](https://github.com/noneplugin/nonebot-plugin-imageutils) 的说明设置字体
