### ISSUE TITLE
建议：建议加个放大缩小分辨率的功能

### ISSUE THREAD

**Issue by atriatri20** [noneplugin/nonebot-plugin-petpet#110]
现在petpet好多都是默认生成大小为500px宽，生成jpg那些表情还好，生成gif的有些就觉得好大了，单独增加个缩小分辨率啥的命令感觉可以

**Comment by MeetWq** [comment]
目前是通过限制帧数来限制gif的大小，有些gif也调整了缩放
如果你觉得哪些表情比较大的话可以提出来，我再调整一下缩放
但放到命令里面感觉不太合适

**Comment by MeetWq** [comment]
加了gif最大大小和最大帧数的配置项
