### ISSUE TITLE
新的表情包

### ISSUE THREAD

**Issue by Zoe-Wh1t3zZ** [noneplugin/nonebot-plugin-petpet#12]
![咬](https://user-images.githubusercontent.com/94744908/155047620-0c6cf2ec-b2a1-4044-8409-214ad2f52f64.gif)
咬.gif

**Comment by 3273576540** [comment]
可以稍微调慢点duration

**Comment by MeetWq** [comment]
这个感觉不好加头像呀

**Comment by 3273576540** [comment]
![IMG_20220301_114034](https://user-images.githubusercontent.com/94744908/156869559-4de56fda-a495-4850-b064-33d249ee6463.jpg)
背景和手机里的照片 换QQ头像，Zoe新小白白白换群昵称
感觉难度有点大

**Comment by MeetWq** [comment]
> ![IMG_20220301_114034](https://user-images.githubusercontent.com/94744908/156869559-4de56fda-a495-4850-b064-33d249ee6463.jpg) 背景和手机里的照片 换QQ头像，Zoe新小白白白换群昵称 感觉难度有点大

我可以试试
感觉背景用QQ头像会比较违和

**Comment by 3273576540** [comment]
![image](https://user-images.githubusercontent.com/94744908/156873997-3a93770c-21ab-4930-a689-71d5ac3d807d.png)
渐变国旗头像

**Comment by MeetWq** [comment]
> ![image](https://user-images.githubusercontent.com/94744908/156873997-3a93770c-21ab-4930-a689-71d5ac3d807d.png) 渐变国旗头像

这个有示例吗

**Comment by 3273576540** [comment]
![image](https://user-images.githubusercontent.com/94744908/156875097-5f436416-ed23-43d8-b820-359b85b4bba8.png)

**Comment by 3273576540** [comment]
![4a72-iytwsca5448375](https://user-images.githubusercontent.com/94744908/156877200-d616c051-b21b-48d3-bb34-91f1842095ab.jpg)

**Comment by MeetWq** [comment]
> 背景和手机里的照片 换QQ头像，Zoe新小白白白换群昵称 感觉难度有点大

目前效果如下，可以给个关键词吗？想不出用什么合适
![result.jpg](https://s2.loli.net/2022/03/09/s2W7FBCgkEtrS1b.jpg)

**Comment by 3273576540** [comment]
交个朋友.jpg

**Comment by 3273576540** [comment]
还有一个新的   抛/扔/掷@某人
![Cache_1baac51f3071f05c](https://user-images.githubusercontent.com/94744908/157442880-c2d758dd-93a8-4727-b380-9d008b1ad5db.jpg)

**Comment by 3273576540** [comment]
[抛.zip](https://github.com/MeetWq/nonebot-plugin-petpet/files/8214751/default.zip)

**Comment by 3273576540** [comment]
抛/扔/掷@xxx
![QQ图片20220309203708](https://user-images.githubusercontent.com/94744908/157445049-8bc11852-7035-41ce-854c-d5844e29fa95.gif)

**Comment by jcjrobert** [comment]
墙纸纵坐标不对，改一下（）

**Comment by MeetWq** [comment]
> 墙纸功能纵坐标不对 还有交个朋友参数设置没有

墙纸是因为那个裂缝横向宽度太大了，所以纵向只能显示一小部分（
所以怎样放更好一些？

**Comment by jcjrobert** [comment]
> 

我改成330了，仅供参考

**Comment by 3273576540** [comment]
我这交个朋友还是没反应

**Comment by leinlin** [comment]
> > 
> 
> 我改成330了，仅供参考

**Comment by leinlin** [comment]
> > 墙纸功能纵坐标不对 还有交个朋友参数设置没有
> 
> 墙纸是因为那个裂缝横向宽度太大了，所以纵向只能显示一小部分（ 所以怎样放更好一些？

async def wallpaper(users: List[UserInfo], **kwargs) -> BytesIO:
    img = users[0].img

    bg = await load_image("wallpaper/0.png")
    tmp_bg = bg
    bw, bh = bg.size
    bg = resize(bg, (int(0.45 * bw), int(0.45 * bh)))
    bw, bh = bg.size
    tmp_bg.close()
    w, h = img.size

    h1 = int(bh / 2)  #墙纸的高度
    w1 = int(float(w) / float(h) * h1) #墙纸的长度
    if w1 < 400:
        w1 = 400
        h1 = int(float(h) / float(w) * 400)

    posX = int((bw - w1) / 2) #墙纸的中心要做 背景的中心
    if posX >= 25:
        posX = posX + posX - 25  # 墙纸的中心要做 背景的中心

    poxY = int( (bh - h1) * 0.65 + (bh / 2) * 0.35)
    def paste(img: IMG) -> IMG:
        img = to_jpg(img)
        frame = Image.new("RGB", bg.size, (255, 255, 255))
        imx = resize(img, (w1, h1))
        img.close()
        frame.paste(imx, (posX, poxY))
        imx.close()
        frame.paste(bg, mask=bg)
        return frame

    if not getattr(img, "is_animated", False):
        return save_jpg(paste(img))
    else:
        frames = []
        shrinkTime = float(img.n_frames) / 70

        for i in range(img.n_frames):
            if shrinkTime > 1:
                if shrinkTime*i >= img.n_frames:
                    break
                img.seek(int(shrinkTime * i))
                frames.append(paste(img))
            else:
                img.seek(i)
                frames.append(paste(img))

        bg.close()
        img.close()

        duration = img.info["duration"]
        if shrinkTime > 1:
            duration = min(duration * shrinkTime, 280)

        return save_gif(frames, duration / 1000)

我这个算法自适应了，可以无视图片的长宽，直接把图片中间黄金分割的部分 显示给用户

**Comment by MeetWq** [comment]
> 我这个算法自适应了，可以无视图片的长宽，直接把图片中间黄金分割的部分 显示给用户

我现在写的逻辑是保证完全覆盖裂缝，然后居中

**Comment by Zoe-Wh1t3zZ** [comment]
![215dce11d322e50f](https://user-images.githubusercontent.com/94744908/157849117-b62a3ebb-9f16-4618-a20b-fd860be3aede.png)

**Comment by Zoe-Wh1t3zZ** [comment]
![gif_2022_0315_135703](https://user-images.githubusercontent.com/94744908/158316325-c242785c-c0f3-4f4f-99f7-6200c1be4124.gif)

差不多的把天星换成头像

天动万象.gif

**Comment by Zoe-Wh1t3zZ** [comment]
还可以做个类似于剧照的
头像做成剧情截图然后配句字幕

**Comment by MeetWq** [comment]
> 还可以做个类似于剧照的 头像做成剧情截图然后配句字幕

不是很了解，建议pr（

**Comment by leinlin** [comment]
![图片](https://user-images.githubusercontent.com/30318270/160287582-f8b67cc6-8939-44f0-be3a-5e62ef40af66.png)
小废狗

**Comment by MeetWq** [comment]
> ![图片](https://user-images.githubusercontent.com/30318270/160287582-f8b67cc6-8939-44f0-be3a-5e62ef40af66.png) 小废狗

这个我感觉更适合放到 memes 里去

**Comment by leinlin** [comment]
小画家
![image](https://user-images.githubusercontent.com/30318270/170905368-b585930e-fc60-4e0d-a9d2-e3fccef87188.png)

**Comment by Qiuyebai-1226** [comment]
![QQ图片20220604183214](https://user-images.githubusercontent.com/62199231/171995409-4abc0056-07f8-40a6-970d-e4a996132c5a.jpg)
没有你我可怎么活啊，**！
