### ISSUE TITLE
看书文字能不能竖起来排列

### ISSUE THREAD

**Issue by leinlin** [noneplugin/nonebot-plugin-petpet#120]
![~U`XB)IO1SDYV6 R8}5Y BC](https://user-images.githubusercontent.com/30318270/186414858-5e6960f2-1085-417a-a9ab-0a0cb1343b30.PNG)

**Comment by MeetWq** [comment]
我试过把逐个字符竖着排列，但对英文不友好

**Comment by MeetWq** [comment]
而且文字太多竖着排的话字会很小

**Comment by MeetWq** [comment]
ad45e0438a4f1feedea0150c56e616d03bd347d5
