### ISSUE TITLE
如何不加载nonebot在外部使用

### ISSUE THREAD

**Issue by inspire-boy** [noneplugin/nonebot-plugin-petpet#121]
如何不加载nonebot在外部使用，只传入一个图片和字符（摸）返回gif的？

**Comment by MeetWq** [comment]
暂时没法这样，你可以自行魔改

**Comment by inspire-boy** [comment]
> 

建议后续能解耦一下，这样用途广一些，现在每个文件都再import nonebot ~~

**Comment by MeetWq** [comment]
目前表情制作相关逻辑已移至 https://github.com/MeetWq/meme-generator，可以独立使用
nonebot 这边由 https://github.com/noneplugin/nonebot-plugin-memes/tree/v0.4.x 对接
欢迎使用

**Comment by inspire-boy** [comment]
> 

给力！！您的工作太有价值了
