### ISSUE TITLE
如何更新插件？

### ISSUE THREAD

**Issue by ShanShuWu** [noneplugin/nonebot-plugin-petpet#122]
您好，我很喜欢这个插件，如果这个插件的内容更新我应该如何将新内容应用到本地？抱歉，我是一个新手，我还没有遇到过插件更新的情境。

**Comment by MeetWq** [comment]
如果你是pip装的，
```
pip install -U nonebot_plugin_petpet
```

**Comment by ShanShuWu** [comment]
我好像是直接用nb安装的，我不知道重复使用安装命令会不会出现already exist那种报错

**Comment by MeetWq** [comment]
用nb装的话可以
```
nb plugin update nonebot_plugin_petpet
```
实际上nb也是调用pip，只是会帮你改 `pyproject.toml` 文件而已
注意 `pyproject.toml` 和 `bot.py` 里面不要重复就行

**Comment by ShanShuWu** [comment]
感谢！我明白了！
