### ISSUE TITLE
看书出现字母就显示 文字过长

### ISSUE THREAD

**Issue by leinlin** [noneplugin/nonebot-plugin-petpet#123]
![image](https://user-images.githubusercontent.com/30318270/188055079-0669f2d2-c910-43e3-aa95-d92da6d1060f.png)

**Comment by MeetWq** [comment]
我这边没法复现这个问题，看看日志？

**Comment by jcjrobert** [comment]
我这边也有，而且看日志也没有什么报错，估计是我设置的日志等级导致没看到

**Comment by jcjrobert** [comment]
把w>240改成w>265就行了
