### ISSUE TITLE
迷惑的 第0帧和第99帧 变化太大有点衔接不起来

### ISSUE THREAD

**Issue by leinlin** [noneplugin/nonebot-plugin-petpet#128]
![image](https://user-images.githubusercontent.com/30318270/189824501-94fecd89-0bee-47ba-bd77-31f789b401b1.png)

**Comment by SEAFHMC** [comment]
如果要无缝衔接的话可能要300帧（

**Comment by leinlin** [comment]
> 如果要无缝衔接的话可能要300帧（

我看你的66帧的那个衔接就不错

**Comment by SEAFHMC** [comment]
> 我看你的66帧的那个衔接就不错

是这样的；原视频21秒共630帧，刚开始的版本为了减小GIF大小所以抽帧出来了66帧，为了保证画面流畅度GIF速度其实是三倍速播放的否则看起来会很“顿”。

但是感觉播放速度慢一些更好营造“大脑短路”的效果，所以后来又减少了播放时间并放慢了播放速度。
