### ISSUE TITLE
典中典的日语翻译模块不太稳

### ISSUE THREAD

**Issue by lkfun** [noneplugin/nonebot-plugin-petpet#129]
我用原版的翻译会报错，返回
`The URL has moved <a href="http://dog.youdao.com/?product=fanyi&url=http%3A%2F%2Ffanyi.youdao.com%2Ftranslate%3Fsmartresult%3Ddict%26smartresult%3Drule%26type%3DZH_CN2JA%26i%3D1%26doctype%3Djson">here</a>`

我参考[这里](https://github.com/XingHaossssssss/Corpus/blob/a9cbc793a1b3082d0d4e2b704ebc513fc4e1847e/translatetext.py)重新写了翻译的方法，目前稳定了。

**Comment by MeetWq** [comment]
已更换为百度翻译
