### ISSUE TITLE
新的表情包 定制

### ISSUE THREAD

**Issue by leinlin** [noneplugin/nonebot-plugin-petpet#130]
![$K~8R 6_WR% MTXS}TSL`76](https://user-images.githubusercontent.com/30318270/192202831-2bcecffd-5a00-43b6-a766-70e32c3202c5.jpg)
现在是幻想时间
莹妹可以默认是自己，然后幻想的涩图 半透明一下

**Comment by jcjrobert** [comment]
感觉彩色背景放上会很突兀，如果是空白背景就还好，就像你发的图，然而大部分应该都不是空白背景
