### ISSUE TITLE
个别账号会报异常且不会发送图片

### ISSUE THREAD

**Issue by ddlixin** [noneplugin/nonebot-plugin-petpet#131]
![屏幕截图 2022-09-27 011818](https://user-images.githubusercontent.com/49864556/192342513-b610c89f-0529-4f6c-8ffb-4f79c9b3e3f7.png)
这个状况以前没出现过，更新为3.1版本后会弹这个错误。报错的账号，大多是以英文名开头

**Comment by SEAFHMC** [comment]
看看gocq，是不是风控了【

**Comment by ddlixin** [comment]
> 看看gocq，是不是风控了【

CQ上显示风控了。不太懂CQ风控机制，就是单独几个账号，特定的几个表情不能发。比如： 
rua@账号A ，不能发送✘；
rua@账号B ，可以发送✔；
亲@账号A，可以发送 ✔；

**Comment by MeetWq** [comment]
这个应该不是插件的锅
有可能是特定图片被风控了
