### ISSUE TITLE
帮助图文字显示异常

### ISSUE THREAD

**Issue by Kiana1314** [noneplugin/nonebot-plugin-petpet#133]
![HO@IB`~}T2)WCBM$(_BU}9D](https://user-images.githubusercontent.com/107671434/193465506-d9edf76d-f650-4853-92b4-4b8dfd2fc601.png)

**Comment by MeetWq** [comment]
这个字符是emoji，可以参考[nonebot-plugin-imageutils](https://github.com/noneplugin/nonebot-plugin-imageutils)的说明添加emoji字体
