### ISSUE TITLE
这图适合拿来加文字，不知道有没有人做

### ISSUE THREAD

**Issue by liuzj288** [noneplugin/nonebot-plugin-petpet#135]
![1f0f16d5e0104b439f584c4e0a45a7041664718208689](https://user-images.githubusercontent.com/13833404/193467758-f66c47d7-d807-446e-bb16-e2a569d0dbd5.jpeg)

**Comment by SEAFHMC** [comment]
只是加文字的话可以去[nonebot-plugin-memes](https://github.com/noneplugin/nonebot-plugin-memes)

**Comment by MeetWq** [comment]
已在 [nonebot-plugin-memes](https://github.com/noneplugin/nonebot-plugin-memes) 中添加
