### ISSUE TITLE
image文件夹素材不够（？）

### ISSUE THREAD

**Issue by daguazi** [noneplugin/nonebot-plugin-petpet#136]
![_1NV@CAX(M{1QM LFWTPA_V](https://user-images.githubusercontent.com/94371464/193615078-319a830e-dbaf-40ac-ab78-c2c7377b8bb9.PNG)
![image](https://user-images.githubusercontent.com/94371464/193615260-fec07f74-2008-44cc-a698-f2cebe9c5547.png)
有84个表情包，但是在image文件夹里却只有69个表情包的素材，是我哪里搞错了吗？我是今天发现“典中典”用不了，然后去看了一下才发现的，亦或者说其实有一些表情不需要素材？只是我“典中典“不知为何用不了？

**Comment by MeetWq** [comment]
有些表情不需要素材
“典中典”可能是翻译api的原因，我改成了百度翻译，需要自行注册并设置appid和key，可以看“配置项”的说明
