### ISSUE TITLE
想问一下触发指令怎么修改

### ISSUE THREAD

**Issue by 1776304537** [noneplugin/nonebot-plugin-petpet#137]
例如 原来是 摸+@某某人 ，我想改成 @某某人+摸

**Comment by MeetWq** [comment]
目前的触发方式都是指令在在前的，因为指令后可能有多个值，比如有的表情可以指定多个目标，有的表情可以加参数等，要改成@在前并不是很好改

**Comment by 1776304537** [comment]
![QQ截图20221004181711](https://user-images.githubusercontent.com/24807330/193801045-d1affa22-dcd1-4c3a-af03-2137155ba879.jpg)
因为我看有机器人就是这样触发的...

**Comment by MeetWq** [comment]
![Snipaste_2022-10-04_19-00-54](https://user-images.githubusercontent.com/33149974/193802743-eda3d183-a641-4943-9d17-0b1cf44e100e.png)
我觉得目前的触发方式很明确啊，为什么一定要@在前？如果想用qq号触发呢？

**Comment by 1776304537** [comment]
只是我们一部分人发送的习惯就是先@再加文字指令，然后看到有机器人实现了这种触发方式就来问问的...

**Comment by 1776304537** [comment]
还有个问题就是关于撕的表情，要把滑稽换成自己头像，那段代码和现在文件里的好像不匹配
