### ISSUE TITLE
为什么发送指令+@之后报错OSError: broken data stream when reading image file

### ISSUE THREAD

**Issue by leyandh** [noneplugin/nonebot-plugin-petpet#154]
![image](https://user-images.githubusercontent.com/72337047/198946018-d65cb5c9-0dc0-4685-b16a-c36c1564c080.png)

**Comment by MeetWq** [comment]
能不能稳定复现？多试几次，换别的表情试试呢？

**Comment by leyandh** [comment]
之前是只有一个命令不文明才出现，用几次后全部都是这种错误

**Comment by MeetWq** [comment]
是特定的头像有问题还是都有问题？

**Comment by leyandh** [comment]
所有的

**Comment by leyandh** [comment]
刚才把PIL全部装好之后变成
![image](https://user-images.githubusercontent.com/72337047/200104134-303ef9a6-5dfb-4891-8c31-1e7ae106603d.png)

**Comment by MeetWq** [comment]
> 刚才把PIL全部装好之后变成 ![image](https://user-images.githubusercontent.com/72337047/200104134-303ef9a6-5dfb-4891-8c31-1e7ae106603d.png)

这个需要升级 nonebot_plugin_imageutils，版本 0.1.13.2 修了

**Comment by leyandh** [comment]
阿里嘎多！
