### ISSUE TITLE
表情包”小天使“在制作动图时显示异常

### ISSUE THREAD

**Issue by jcjrobert** [noneplugin/nonebot-plugin-petpet#159]
![%61T8`R4$8T3P1AO$LX29D4](https://user-images.githubusercontent.com/52129454/200554155-5e65d7da-d3c9-4aec-9dcb-ad2dbff7ffc3.PNG)
即使背景设置为RGB也不能解决问题（嵌套使用时依然会有）

**Comment by MeetWq** [comment]
8535c62de672c6414e0e6bd83f3c8db0da2467f4 理论上解决了
