### ISSUE TITLE
ModuleNotFoundError: No module named 'emoji.core'

### ISSUE THREAD

**Issue by Crystal03Up** [noneplugin/nonebot-plugin-petpet#162]
I have already downloaded the latest version of emoji, and I've checked that there is a __init__.py in the directory; yet I cannot import the emoji.core when importing stanza. What to do with it?
![image](https://user-images.githubusercontent.com/78154690/203988532-1ac46049-c9d9-4463-9146-3218ea46bbd3.png)

**Comment by MeetWq** [comment]
Are you sure you're asking the question in the right place?
The latest version of `nonebot_plugin_petpet` no longer needs `emoji`.
