### ISSUE TITLE
无法响应"头像表情包"指令

### ISSUE THREAD

**Issue by Mira-LeafTown** [noneplugin/nonebot-plugin-petpet#163]
群内无响应，终端看起来也没有
![Screenshot_20221202-161247~2](https://user-images.githubusercontent.com/87133530/205247279-f07dfcd3-3064-4c88-bc83-bade156d2f04.png)

**Comment by MeetWq** [comment]
其他指令能触发吗？
大概率是和你别的插件冲突了

**Comment by Mira-LeafTown** [comment]
> 其他指令能触发吗？ 大概率是和你别的插件冲突了

可以，除了"头像表情包"不行

**Comment by MeetWq** [comment]
截一下完整日志，看最后一个响应“头像表情包”命令的是什么插件

**Comment by Mira-LeafTown** [comment]
> 截一下完整日志，看最后一个响应“头像表情包”命令的是什么插件

重新看了一下，是赛马娘插件的表情包命令，删了就解决了
