### ISSUE TITLE
No module named 'nonebot_plugin_imageutils.gradient'

### ISSUE THREAD

**Issue by a930389426** [noneplugin/nonebot-plugin-petpet#171]
![image](https://user-images.githubusercontent.com/59648220/208627973-57679537-517c-4218-ac45-dde1c7725be3.png)

**Comment by MeetWq** [comment]
升级nonebot-plugin-imageutils

**Comment by a930389426** [comment]
> 升级nonebot-plugin-imageutils

我的imageutils就是刚才从github上下载的，已经是最新的了

**Comment by MeetWq** [comment]
imageutils最好用pip下载，直接放插件文件夹的话引用路径不对

**Comment by a930389426** [comment]
> imageutils最好用pip下载，直接放插件文件夹的话引用路径不对

我刚才改用了pip下载，也是不行。
哪个function.py源代码是这样的

from nonebot_plugin_imageutils import Text2Image
from nonebot_plugin_imageutils.fonts import Font
from nonebot_plugin_imageutils.gradient import LinearGradient, ColorStop

我报错的gradient是第三个引用的，那么说明前两个引用应该是没问题的，偏偏第三个有问题，这我就不知道怎么搞了

**Comment by MeetWq** [comment]
检查一下 nonebot-plugin-imageutils 版本是否在"0.1.13.2"以上
