### ISSUE TITLE
“头像表情包”指令报错

### ISSUE THREAD

**Issue by Cvandia** [noneplugin/nonebot-plugin-petpet#189]
详细如下
![(ICIJMX0$MF7@()NPUMK)OJ](https://user-images.githubusercontent.com/106718176/214223373-be1fe1e5-3c04-46c9-9afc-0e5e8a9410a2.png)
![WY@BB FC7MXYR}4}IKJA7_P](https://user-images.githubusercontent.com/106718176/214223384-2e67add6-c548-403d-98b7-13ecb89e5ad5.png)

**Comment by MeetWq** [comment]
你的字体是怎么设置的？pillow不支持SVG字体

**Comment by Cvandia** [comment]
> 你的字体是怎么设置的？pillow不支持SVG字体

是指系统安装的字体吗？

**Comment by MeetWq** [comment]
> 是指系统安装的字体吗？

指 [nonebot-plugin-imageutils](https://github.com/noneplugin/nonebot-plugin-imageutils) 设置的字体

**Comment by Cvandia** [comment]
> 

插件imageutils没有进行```.env```的相关配置，只在```/data/fonts```中添加如下的字体
![image](https://user-images.githubusercontent.com/106718176/214260698-e938412f-fc06-4f3d-a1cb-5baf02b83e0e.png)

**Comment by MeetWq** [comment]
把 `NotoColorEmoji-Regular.ttf` 重命名为 `NotoColorEmoji.ttf`

**Comment by Cvandia** [comment]
貌似未解决问题，尝试过移除多余的字体，依旧报同样的错误

**Comment by MeetWq** [comment]
![Snipaste_2023-01-27_19-42-02](https://user-images.githubusercontent.com/33149974/215078118-29cac2e8-5860-4227-82cf-f68bfc0dff0b.png)
你在 `nonebot_plugin_imageutils/text2image.py` 47行这里加一句，把字体名打出来，看是什么字体的问题

**Comment by Cvandia** [comment]
![image](https://user-images.githubusercontent.com/106718176/215080429-2bc40dee-97a8-44dd-8069-e53183a29da5.png)
QWQ

**Comment by MeetWq** [comment]
看看有报错的地方打印的什么

**Comment by Cvandia** [comment]
问题已解决，是```NotoColorEmoji.ttf```版本下错了，下成```SVG```版本了，感谢作者大大提醒

**Comment by Cvandia** [comment]
替换后成功显示菜单图
