### ISSUE TITLE
在windows server2012系统的服务器上安装插件失败，提示Failed to import "nonebot_plugin_imageutils"

### ISSUE THREAD

**Issue by Ble55me** [noneplugin/nonebot-plugin-petpet#195]
在本地环境中可以正常运行，但是在服务器环境中安装就会报错，说找不到指定模块，日志如下，想问下大佬服务器环境是不是缺了什么依赖，有什么解决方式
[log.txt](https://github.com/noneplugin/nonebot-plugin-petpet/files/10769137/log.txt)

**Comment by Plasma4004** [comment]
这是系统问题，server2012确实有丢包的

**Comment by Ble55me** [comment]
想问下大佬这种情况下需要补哪些包才能解决呢？还是说只有升级更新的系统才能解决这样子

**Comment by MeetWq** [comment]
参考 https://github.com/opencv/opencv-python#frequently-asked-questions
