### ISSUE TITLE
No module named 'nonebot_plugin_imageutils'

### ISSUE THREAD

**Issue by tyx3** [noneplugin/nonebot-plugin-petpet#198]
插件加载不了，前置插件nonebot_plugin_imageutils也已经安装并未报错
![QQ图片20230228225008](https://user-images.githubusercontent.com/53116313/221889396-64fb4ac6-b58b-4d46-8af3-b2c63c31739c.png)
不知道是什么问题，求大佬指点一下

**Comment by MeetWq** [comment]
你的 nonebot_plugin_imageutils 是pip装的还是手动放到插件文件夹里的？

**Comment by tyx3** [comment]
手动的，刚刚找到一个老的issues，然后pip试着装了一下，没有报错了，问题解决了，前面没直接搜报错，没看见原先解决的问题

**Comment by tyx3** [comment]
我的问题（悲
