### ISSUE TITLE
不如

### ISSUE THREAD

**Issue by 863109569** [noneplugin/nonebot-plugin-petpet#45]
![28(PL0FUY@_{LW%TKDE@GU8](https://user-images.githubusercontent.com/77315378/160433738-8a9fc933-8f48-4008-90b5-82179c77b768.jpg)

**Comment by 863109569** [comment]
另外您的wordle老是找不到单词，更新最新版也没用，例如mold,honor，但是答案又是这些单词（

**Comment by MeetWq** [comment]
> 另外您的wordle老是找不到单词，更新最新版也没用，例如mold,honor，但是答案又是这些单词（

我试了是没问题的呀

![Snipaste_2022-03-29_00-16-15.png](https://s2.loli.net/2022/03/29/8xw7WY3l2pmX9qd.png)
![Snipaste_2022-03-29_00-16-36.png](https://s2.loli.net/2022/03/29/g5kqzlD9Z8wOUAS.png)

**Comment by 863109569** [comment]
![image](https://user-images.githubusercontent.com/77315378/160507411-a9950335-1aa7-49cc-bd27-5c6a438518a6.png)
不知道为啥，我也更新了最新的版本，这也是私聊的时候发的（
