### ISSUE TITLE
添加表情 啾啾

### ISSUE THREAD

**Issue by Yonnemy2nd** [noneplugin/nonebot-plugin-petpet#48]
抠的一个gif，希望能整一下。
https://user-images.githubusercontent.com/89773516/163322401-6a9c7b4e-74b0-405f-a8ff-435d7811be9f.gif

**Comment by MeetWq** [comment]
这个感觉有点抽象啊，有无原图

**Comment by Yonnemy2nd** [comment]
原图是
![{`VGTDB{F`C2HYGP D2NQJ3](https://user-images.githubusercontent.com/89773516/163338163-5fcb93ba-38bf-4c6f-b720-cc49f83fe5ae.gif)
