### ISSUE TITLE
希望增加

### ISSUE THREAD

**Issue by othinus001** [noneplugin/nonebot-plugin-petpet#54]
图片拆九宫格，拆几份变成一条条的，可以加入图片操作，还有倒放gif

**Comment by MeetWq** [comment]
是指分割成9张图片吗

**Comment by othinus001** [comment]
> 

是的，类似微博b站九宫格

**Comment by MeetWq** [comment]
图片操作放到了另一个插件里，九宫格加上了
https://github.com/noneplugin/nonebot-plugin-imagetools
