### ISSUE TITLE
增加模糊识别

### ISSUE THREAD

**Issue by othinus001** [noneplugin/nonebot-plugin-petpet#64]
多群使用观察发现很多人@昵称和QQ号数字混用，所以有时@123456或@自己，希望增加模糊识别。
另兑换券可以加个兑换卷

**Comment by MeetWq** [comment]
这样并不合理啊，毕竟 @别人 和 其他文本 是有区别的，直接复制的 @昵称 也不会生效啊
我还是希望语义尽可能准确，减少误触
