### ISSUE TITLE
QQ发送“头像表情包”没有弹出支持的列表， 后台提示超出范围

### ISSUE THREAD

**Issue by mmmjie** [noneplugin/nonebot-plugin-petpet#68]
![0JZ}X9N@_6YXWV2( 3QT@YU](https://user-images.githubusercontent.com/45615222/171334355-01ff1820-065d-4d72-909f-0cecec2d6c05.png)

实际使用，试了几个表情到是没发现问题，就是 表情包支持列表没有正常显示，前台也无报错

真寻版本：1.58
插件版本：真寻适配0.2 （https://github.com/yajiwa/zhenxun_plugin_petpet）

**Comment by MeetWq** [comment]
这是系统中没有找到指定的字体
看 [nonebot-plugin-imageutils](https://github.com/noneplugin/nonebot-plugin-imageutils) 的说明

**Comment by mmmjie** [comment]
> 这是看系统中没有找到指定的字体 nonebot [-plugin-imageutils](https://github.com/noneplugin/nonebot-plugin-imageutils)的说明

安装 字体包后解决了，感谢！！！
