### ISSUE TITLE
关于“我朋友说”这个表情包

### ISSUE THREAD

**Issue by yoiyami96** [noneplugin/nonebot-plugin-petpet#69]
“我朋友说”这个表情包不能自定义昵称了吗，还是原来的更有意思🥲

**Comment by MeetWq** [comment]
因为我感觉既加名字又加要说的内容比较乱，尤其是想加多句话的时候

**Comment by MeetWq** [comment]
或者我觉得改成 “我朋友 xxx 说 xxx ” 的形式更合理一点

**Comment by yoiyami96** [comment]
> 或者我觉得改成 “我朋友 xxx 说 xxx ” 的形式更合理一点
这个方案好！辛苦大佬这么晚还回复

**Comment by MeetWq** [comment]
> 或者我觉得改成 “我朋友 xxx 说 xxx ” 的形式更合理一点

我把命令改成了正则匹配，现在可以用这种形式了
