### ISSUE TITLE
一些表情包预定

### ISSUE THREAD

**Issue by jcjrobert** [noneplugin/nonebot-plugin-petpet#7]
还没来得及做，先放着

**Comment by jcjrobert** [comment]
![QQ图片20220102232545](https://user-images.githubusercontent.com/52129454/147880559-1f96d467-5140-4107-8d19-eb9038886991.gif)
下面配字：来玩休闲游戏啊
![QQ图片20220102232737](https://user-images.githubusercontent.com/52129454/147880577-6bc9910e-b586-4774-9c1b-c4fdbec43bcb.jpg)

**Comment by jcjrobert** [comment]
![6GQRM2Q4ELNFWRF9(XRUAP7](https://user-images.githubusercontent.com/52129454/147880675-d916e5d5-f35f-4f77-b654-0549636d00f4.jpg)
![%W{JCGK~JNC ${{R11$0NB7](https://user-images.githubusercontent.com/52129454/147880678-c8635b9d-15e0-43eb-a6b6-d11c265c8e1c.jpg)
![~H CW) ( 6YAS`S)5WEQY_0](https://user-images.githubusercontent.com/52129454/147880689-5fdea532-22dd-4f87-99e2-e4bde8dfea6f.jpg)
![N2N8QA)H550AP9((%ZBBOBJ](https://user-images.githubusercontent.com/52129454/147880699-74888bef-d64e-42bd-b6a6-2c3e1e2bf685.jpg)

**Comment by MeetWq** [comment]
![QQ图片20220102232737](https://user-images.githubusercontent.com/52129454/147880577-6bc9910e-b586-4774-9c1b-c4fdbec43bcb.jpg)
这个有没有最终效果的示例？

**Comment by jcjrobert** [comment]
![u=1135731701,2441187104 fm=253 app=138 f=JPEG](https://user-images.githubusercontent.com/52129454/147905352-aa8cb758-f4ee-4f17-a7bd-4ca6e09e92a5.jpg)
这样（）

**Comment by MeetWq** [comment]
另外我感觉下面这些滑稽表情没什么做的必要，首先是太糊，而且滑稽才是灵魂啊（

**Comment by jcjrobert** [comment]
手写变换牛啊，我去搜都是opencv2的

**Comment by jcjrobert** [comment]
本来想看看小天使功能能不能根据性别调整一下文字，但是dict的sex都是unknown

**Comment by MeetWq** [comment]
> 小天使功能加个根据性别调整一下文字吧，我就不提交pr了（）

改了

**Comment by zhzRedstone** [comment]
吃
![OQ_WRQ49$EK}W{{61HI8BBJ](https://user-images.githubusercontent.com/39423408/153833278-d2f8d009-c4b7-443b-bf95-b3631ca4241c.PNG)

啃
![UAZIFJF1S}F2FOC02 H G2N](https://user-images.githubusercontent.com/39423408/153833314-73aca8cf-7682-463e-aaf4-d51fa43f5f76.PNG)

**Comment by MeetWq** [comment]
阿哲，有点血腥（

**Comment by zhzRedstone** [comment]
> 阿哲，有点血腥（

把
![image](https://user-images.githubusercontent.com/39423408/153848418-48c2b587-c9ea-4b5d-b8b6-66fc44b8cc7b.png)
做了可以吗（）

**Comment by MeetWq** [comment]
这两个表情好像椛椛有，我直接去抄（

**Comment by jcjrobert** [comment]
![R$HVMB@A VIS7M$1KT PG17](https://user-images.githubusercontent.com/52129454/155279620-58599edb-769c-4ca0-8223-7719f3fd136e.jpg)
让XX告诉你吧
头像
（XX XX不知道哦。）
啊这，他说不知道

**Comment by leinlin** [comment]
![PUET{K@7)32ES TRAM7%X7D](https://user-images.githubusercontent.com/30318270/157480290-78c83e0e-1cc8-4994-92ca-7940373d7044.jpg)
来个这个，继续干活

**Comment by jcjrobert** [comment]
这像画吗
![这像画吗](https://user-images.githubusercontent.com/52129454/157682217-d570dc30-4acb-4a6c-9b09-59840c1da763.jpg)

因为没搞懂你那仿射变换怎么搞，对四个点没对上就没搞了（（（

**Comment by MeetWq** [comment]
@jcjrobert 写了个震惊，但效果很奇怪，能帮忙看看吗

**Comment by leinlin** [comment]
![6((58OL8$4) KLUP}}VM7X0](https://user-images.githubusercontent.com/30318270/158007766-3801c7c8-5626-4d8b-a81f-bb0d7dadcef6.gif)
数学公式

**Comment by jcjrobert** [comment]
> ![6((58OL8$4) KLUP}}VM7X0](https://user-images.githubusercontent.com/30318270/158007766-3801c7c8-5626-4d8b-a81f-bb0d7dadcef6.gif) 数学公式

这个感觉直接套头像怪怪的，你觉得怎么套比较好

**Comment by leinlin** [comment]
> 

可以把卡通脸挖一个遮罩，然后 直接把头像 贴上去，有个轮廓表示是脸就好了

**Comment by leinlin** [comment]
![image](https://user-images.githubusercontent.com/30318270/158015343-5be8d92f-419e-4084-9f33-df69e602caf8.png)
听音乐

**Comment by jcjrobert** [comment]
> @jcjrobert 写了个震惊，但效果很奇怪，能帮忙看看吗

经实践，用随机数可以实现类似原图的生草效果

**Comment by jcjrobert** [comment]
![Dms0m](https://user-images.githubusercontent.com/52129454/158028905-1cc35c59-6f62-4371-9710-db06ea4c4f3b.gif)
这个能搞不（

**Comment by MeetWq** [comment]
![1.gif](https://s2.loli.net/2022/03/13/YcjfwHXRli7bAGB.gif)

**Comment by jcjrobert** [comment]
> ![1.gif](https://camo.githubusercontent.com/d104576fb446edec9173ed4333886d3839050b7034a8656077ebf5d23418351b/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30332f31332f59636a66774858526c6937624147422e676966)

太对了，就是这味（）

**Comment by leinlin** [comment]
我永远喜欢

**Comment by leinlin** [comment]
![image](https://user-images.githubusercontent.com/30318270/158129171-b96bd4e2-0a66-4e56-b986-0def7e8b5e87.png)

**Comment by jcjrobert** [comment]
![GVZKHS8`BVF0)VUUI{AWH5K](https://user-images.githubusercontent.com/52129454/158314480-6097d579-2179-4b44-8ad0-0661a86f8790.PNG)
@MeetWq 好像左下角有点不对劲，有空修复一下吧（）

**Comment by MeetWq** [comment]
> @MeetWq 好像左下角有点不对劲，有空修复一下吧（）

什么不对劲？屏幕左下角吗

**Comment by jcjrobert** [comment]
![image](https://user-images.githubusercontent.com/52129454/159108523-5ba34708-081a-4823-9e97-1829ab274ab4.png)

**Comment by jcjrobert** [comment]
![4F_@DO6V62O2CWBB A6}PY7](https://user-images.githubusercontent.com/52129454/159108614-5dd0ee09-5979-441a-a143-3588af0009e8.png)
![VX O{F4R0Q7Y9@KN(Z5A_`0](https://user-images.githubusercontent.com/52129454/159108616-09123cd7-078a-41d5-855f-74d580e6a485.png)
![2`OFA(TJ (P(IP2X~M6}X~V](https://user-images.githubusercontent.com/52129454/159108621-0aff66d5-559d-4454-a6b6-ba9c3b89d49e.png)

**Comment by jcjrobert** [comment]
![VX O{F4R0Q7Y9@KN(Z5A_`0](https://user-images.githubusercontent.com/52129454/159108632-4a609b91-3f50-42f6-b331-c00b1ebe4fef.png)

**Comment by jcjrobert** [comment]
文字能加emoji么，虽然这个确实难搞（）

**Comment by leinlin** [comment]
![图片](https://user-images.githubusercontent.com/30318270/159338253-be81b033-3f2d-4d01-af7f-456b8389cccc.png)
击剑

**Comment by leinlin** [comment]
![图片](https://user-images.githubusercontent.com/30318270/159338314-60fa19aa-3bf5-4714-adb1-20a97d632217.png)

**Comment by jcjrobert** [comment]
![-119d338b22438d93](https://user-images.githubusercontent.com/52129454/160452272-0e75cdaa-a84d-4741-884d-a92576cd769d.jpg)
群青的字 歪了

**Comment by jx9468** [comment]
![AA](https://user-images.githubusercontent.com/78193384/161571845-accfafc4-864a-4b78-bff1-93915387e0fa.jpg)
为什么@我

**Comment by jx9468** [comment]
![aa](https://user-images.githubusercontent.com/78193384/161573610-7d0ebbcd-3f91-448e-9a17-3310f9f115d6.gif)
![bb](https://user-images.githubusercontent.com/78193384/161573622-8085f6eb-fc04-49d4-9c88-88eba6ba16da.jpg)
不需要的东西
🥺希望可以减少GIF帧数或者只做单帧

**Comment by wangjiahui1126** [comment]
![)6%D8T8@6PZTC25$TSX}BGY](https://user-images.githubusercontent.com/30306738/161965043-bcad33ad-9bc5-4cb6-8da4-8da25fb644b0.jpg)
     表情包添加希望

**Comment by wangjiahui1126** [comment]
谢谢大佬，希望增加结婚申请表情
![37_RG57CW@OLFHM1`BN5X6V](https://user-images.githubusercontent.com/30306738/169442921-43418867-ae51-476b-90a5-fb92e8adfbd8.png)
包
