### ISSUE TITLE
部分指令无结果响应

### ISSUE THREAD

**Issue by RainChain-Zero** [noneplugin/nonebot-plugin-petpet#70]
## 如何复现

在使用中发现部分指令**无响应结果**，通过在函数起始处打log发现形参为`user: UserInfo = User(), arg: str = Arg()`的指令处理函数均**不会被执行**，如指令“去问问”（ask），“小天使”（littleangel）,"我朋友说"(make_friend)等。

进一步发现，User()函数中的dependency（即`async def dependency(users: Optional[List[UserInfo]] = Users())`）在处理过程中**不会被执行**，而Users()正常执行。

## 非预期情况&&控制台输出

如上，输入相关指令如"/小天使 xxx"时，无响应结果，控制台显示似乎触发后立即停止了（？）
![图片](https://user-images.githubusercontent.com/74779439/171821490-da4a01d0-f2a2-48a9-be54-05fdcec9200d.png)

经检查，**无其他指令冲突**，nonebot-plugin-imageutils能正常工作。

## 其他信息

采用mirai2适配器，非onebot协议，只对原插件做了mirai的适配，未修改逻辑。

除上述指令，其他指令正常工作。

~~当然也可能是协议的问题( 逃~~

**Comment by MeetWq** [comment]
因为插件需要用 `get_group_member_info` 和 `get_stranger_info` 接口来获取用户信息，不知道mirai2适配器有没有对应的接口

**Comment by RainChain-Zero** [comment]
> 

有相关的接口，并做了修改( 测试能够返回正确资料信息

**Comment by MeetWq** [comment]
能否把log等级调到debug再看看输出？

**Comment by RainChain-Zero** [comment]
已经照做，控制台如下显示（似乎确实有点问题×）
![图片](https://user-images.githubusercontent.com/74779439/171827472-36d174ba-a3fb-4634-bc32-7a11ccfa0a5b.png)

**Comment by MeetWq** [comment]
暂时想不出是什么问题，能看看你具体是怎么修改的吗？

**Comment by RainChain-Zero** [comment]
好的，相关修改如下，已标注

#### __init__.py
![图片](https://user-images.githubusercontent.com/74779439/171833469-4fb1e041-002c-46da-ba9b-4e79bc8d02fd.png)

#### depends.py
![图片](https://user-images.githubusercontent.com/74779439/171833950-f3e57566-0433-4ab7-8795-d3e495e54edc.png)
![图片](https://user-images.githubusercontent.com/74779439/171834074-3c26b891-0a22-4547-84dd-f5c20654713d.png)

就这些了( 我已经燃尽了×

**Comment by MeetWq** [comment]
看上去没太大问题，很奇怪

你把 `async def dependency(users: Optional[List[UserInfo]] = Users())` 改成 `async def dependency(users: List[UserInfo] = Users())` 试试

**Comment by RainChain-Zero** [comment]
很遗憾，我在灵感迸发时尝试过这么修改，~~但被现实击垮×~~
![图片](https://user-images.githubusercontent.com/74779439/171838191-fe6425c6-334c-4293-9f9b-fac3d892aa94.png)

我再去参悟参悟，说不定就顿悟了(

**Comment by MeetWq** [comment]
试试 `我永远喜欢` 和 `亲` 这两个指令正不正常

**Comment by RainChain-Zero** [comment]
> 试试 `我永远喜欢` 和 `亲` 这两个指令正不正常

永远喜欢不正常，亲正常

**Comment by RainChain-Zero** [comment]
最新战况，在您的提示和控制台的~~神谕~~中，我参悟了宇宙真理×

它提示类型不匹配，于是我把**所有相关的类型说明都删掉**了，就是`async def dependency(users: Optional[List[UserInfo]] = Users())`改成`async def dependency(users = Users())` 然后`functions.py`里也同样删掉，它居然正常运行了（瞳孔地震）

我看不懂，但我大受震撼，也许我需要点时间理解一下为什么(

总之，感谢大佬的协助！~

![图片](https://user-images.githubusercontent.com/74779439/171841932-000cf15a-b201-4abb-8221-7b2872f7a779.png)

**Comment by MeetWq** [comment]
我还是无法理解为什么类型不匹配
等下我试试用mirai适配器，看是适配器的锅还是别的原因

**Comment by RainChain-Zero** [comment]
> 我还是无法理解为什么类型不匹配 等下我试试用mirai适配器，看是适配器的锅还是别的原因

我也( 这太离奇了，加油

**Comment by MeetWq** [comment]
我找到原因了，mirai适配器的接口返回的“sex”是大写，而我给gender字段加了标注限定范围，所以得加个lower()
![Snipaste_2022-06-03_22-31-12](https://user-images.githubusercontent.com/33149974/171875130-d447a4ce-6701-4ccf-9c32-3731587026e9.png)
![Snipaste_2022-06-03_22-32-04](https://user-images.githubusercontent.com/33149974/171875179-f307be27-9aa2-46aa-bb19-ffe6b2e01a40.png)

**Comment by RainChain-Zero** [comment]
> 我找到原因了，mirai适配器的接口返回的“sex”是大写，而我给gender字段加了标注限定范围，所以得加个lower() ![Snipaste_2022-06-03_22-31-12](https://user-images.githubusercontent.com/33149974/171875130-d447a4ce-6701-4ccf-9c32-3731587026e9.png) ![Snipaste_2022-06-03_22-32-04](https://user-images.githubusercontent.com/33149974/171875179-f307be27-9aa2-46aa-bb19-ffe6b2e01a40.png)

好耶！太细了( 谢谢啦，感觉耗了不少时间× 我下次再看仔细点w
