### ISSUE TITLE
部分图片使用 亲亲 贴贴等功能会报错 

### ISSUE THREAD

**Issue by shlgf** [noneplugin/nonebot-plugin-petpet#71]
![image](https://user-images.githubusercontent.com/70182604/171995098-c827b2d9-4baf-4adf-929f-c2725b4a9ac6.png)
但是我把.square（）加上就不报错了能够使用了 不知道为啥
![I7S D0 I ~0WEV~6OK_}FSX](https://user-images.githubusercontent.com/70182604/171995136-0f2ef86b-5502-445d-b159-62fe86ea1ad6.jpg)

**Comment by MeetWq** [comment]
`circle()` 确实有点问题，我在 [nonebot-plugin-imageutils](https://github.com/noneplugin/nonebot-plugin-imageutils) 里修一下，到时更新一下

**Comment by MeetWq** [comment]
已经修了，更新一下 nonebot-plugin-imageutils

**Comment by shlgf** [comment]
我这边更新了还是一样的报错 我提供一下图片
![QQ图片20220604192705](https://user-images.githubusercontent.com/70182604/171996974-c4d95407-46fd-4e53-bce9-e3f3f47d3cf3.jpg)

**Comment by MeetWq** [comment]
我这边试了是没问题的呀

**Comment by shlgf** [comment]
的确是好了不好意思，之前更新的 nonebot-plugin-imageutils 和虚拟环境中zhenxun bot调用的还不是一个路径，这次更新对位置是好的可以用的了。
