### ISSUE TITLE
新表情包预定和讨论专楼

### ISSUE THREAD

**Issue by MeetWq** [noneplugin/nonebot-plugin-petpet#72]
可以提供表情包素材，当然更欢迎直接pr，毕竟抠图还是很麻烦的

预定表情包时，需要提供：
 - 关键词
 - 表情包原图
 - 表情包效果图，或者说明在什么地方添加头像

注意事项：
 - 表情包需要用到用户的头像或自定义图片，如果是单纯的添加文字，可以添加到 [nonebot-plugin-memes](https://github.com/noneplugin/nonebot-plugin-memes)
 - 由于用户的头像千差万别，某些表情包可能很难达到预期的效果。
    - 表情上最好有现成的圆形或方形区域用来放置头像，如“听音乐”、“继续干活”
    - 直接以用户头像做背景的表情对头像要求较高，但若最终效果比较好也可以接受，如“交个朋友”、“结婚申请”
    - **尽量避免直接在图像上加头像的表情**，可能会比较违和，如“为什么@我”
    - 咖波的表情包真好用（
 - 不接受低俗、政治相关的表情
 - 避免太模糊的表情、过于小众的表情、无明显意义的表情
 - 最终是否添加视实际效果和作者的心情决定（

**Comment by leinlin** [comment]
![image](https://user-images.githubusercontent.com/30318270/172081911-2fc09d1d-3c24-46ac-8773-9e7457e8cd79.png)
我要玩 XXX,替换掉游戏图片以及 下面的文字

**Comment by leinlin** [comment]
![V2I ~3QKZ}$QY}F H5UCEXT](https://user-images.githubusercontent.com/30318270/172084377-85b492a7-456b-4403-b7c7-9f4805931219.jpg)
打工莹

**Comment by jcjrobert** [comment]
> ![image](https://user-images.githubusercontent.com/30318270/172081911-2fc09d1d-3c24-46ac-8773-9e7457e8cd79.png) 我要玩 XXX,替换掉游戏图片以及 下面的文字

下面一整行换掉更好，这样可以对人

**Comment by leinlin** [comment]
![image](https://user-images.githubusercontent.com/30318270/172113282-13b65786-cb7c-4687-bd65-973b2351faad.png)

生活美满的网友路过

**Comment by MeetWq** [comment]
> ![image](https://user-images.githubusercontent.com/30318270/172113282-13b65786-cb7c-4687-bd65-973b2351faad.png)

这个是什么意思

**Comment by MeetWq** [comment]
> ![V2I ~3QKZ}$QY}F H5UCEXT](https://user-images.githubusercontent.com/30318270/172084377-85b492a7-456b-4403-b7c7-9f4805931219.jpg) 打工莹

这个感觉重复了，应该不会加了

**Comment by Danwk2333** [comment]
能考虑加个龙图吗，关键字 龙图 自己，龙图 at别人，效果是在头像中间覆盖龙玉涛表情形成新的龙图
![longtu](https://user-images.githubusercontent.com/106854600/172423630-0d614265-ccaf-43b4-a57e-d3a731f38103.png)
![f761fc9869999169ae96b181a1fc129bafacad17_raw](https://user-images.githubusercontent.com/106854600/172423810-ecc19efe-3f8b-414b-86e8-b0fffa3e4219.jpg)

**Comment by LoCCai** [comment]
希望作者考虑一下这个API：
https://xiaobai.klizi.cn/doc.php?name=%E7%A5%AD%E6%8B%9C
https://xiaobai.klizi.cn/doc.php?name=%E5%95%83

**Comment by SinKy-Yan** [comment]
关键词：横幅
效果的话要不不一定加头像？可以变成一串自定义文字
![DF9BEEAF4541DD4A94ACE71AA610B0F5](https://user-images.githubusercontent.com/56128013/172866417-e826e8f5-5b1f-4746-91fc-d6e7e0893e72.png)

**Comment by MeetWq** [comment]
> 关键词：横幅 效果的话要不不一定加头像？可以变成一串自定义文字

纯加文字去 [nonebot-plugin-memes](https://github.com/noneplugin/nonebot-plugin-memes)，这个已经有了

**Comment by jcjrobert** [comment]
考虑加个字符画吗，代码可参考：
https://github.com/RafuiiChan/nonebot_plugin_charpic/blob/main/nonebot_plugin_charpic/data_source.py

**Comment by jcjrobert** [comment]
还有一个希望 远离以下头像的人 上面的文字可以定制（修改）

**Comment by Qiuyebai-1226** [comment]
![R$1AMTQN}HUX@E 6AH5Z)OC](https://user-images.githubusercontent.com/62199231/177243168-6a83e9e5-3459-43f0-8bd5-4ee6a274b8b9.gif)
wq佬考虑加个特技，万花镜

**Comment by Danwk2333** [comment]
![259BCB5B70AB515E031A6D0AA518DB5B](https://user-images.githubusercontent.com/106854600/178235893-1d0545fb-b9dc-44de-9a66-95c7ef8e54c4.jpg)
![7732E685327DC62D0D355599AAA42268](https://user-images.githubusercontent.com/106854600/178236081-fdcbc4a3-f0e2-4f8e-b1c4-f3b6956280b2.jpg)
![6864AD7C0F5B29DC3542F3060B93A2E9](https://user-images.githubusercontent.com/106854600/178236104-54e28134-edde-47e2-bf38-71ddbcfa045d.jpg)
![1F08B4A28CCA43C01F39DD2E898FD4B4](https://user-images.githubusercontent.com/106854600/178236121-fd0bdd75-2eb0-4345-ad0d-35ca638d8f79.jpg)
![2FEA51EAEAF64DD94FB2883A687A86DD](https://user-images.githubusercontent.com/106854600/178236133-41be056f-20b8-4612-ae6c-81b3c0ca1245.jpg)
![BA4BAE75CAEFBDECF2FB11CB5BB832F5](https://user-images.githubusercontent.com/106854600/178236153-582b4724-6ff3-4868-beff-62dfcc4f03f9.jpg)
![BB39F528232BD6ED67B7A814CE694DE3](https://user-images.githubusercontent.com/106854600/178236176-1cebe128-5755-485d-ae1a-fcf26f5f5f5b.jpg)
![5BFA295F1FA7BDE03CD83FA18F7C6AEA](https://user-images.githubusercontent.com/106854600/178236206-1b4fbd12-8dea-4d6e-a954-a917282d09e6.jpg)
mq佬考虑加个图片置于头像上加个自定义文字，
双手 自己 让我捏捏你的屁股

**Comment by balh55y** [comment]
「我朋友说」可以扩展一下,做成对话图
比如「我朋友说」at1 at2
1:阿巴巴巴
1:巴拉巴拉
2:阿巴巴
然后做成一左一右

**Comment by MeetWq** [comment]
> 「我朋友说」可以扩展一下,做成对话图 比如「我朋友说」at1 at2 1:阿巴巴巴 1:巴拉巴拉 2:阿巴巴 然后做成一左一右

这样逻辑太复杂了，或许可以单独做个插件

**Comment by leinlin** [comment]
![origin_img_v2_3472271b-ff6c-4b95-bbdd-61911d4963cg](https://user-images.githubusercontent.com/30318270/182335798-bdc2608f-9ef2-40f2-b646-4cf979e03af1.gif)
把纸替换成图片 
触发命令：狗都不用|嫌弃

**Comment by leinlin** [comment]
![5L94E GXGELHYL`3T)8HM4N](https://user-images.githubusercontent.com/30318270/182757208-a2dff41f-dca9-4152-a980-4d12ed464fd6.gif)
眼睛里滚动一个 复读聊天记录

**Comment by othinus001** [comment]
共进晚餐
![微信图片_20220804210156](https://user-images.githubusercontent.com/38730318/182853512-11ccecdc-5f0b-4945-89ac-ecc9351d7578.jpg)

**Comment by FlashKiana** [comment]
![-35b9e4cfd786ac14](https://user-images.githubusercontent.com/24948734/184127882-f27538f5-34d2-40e9-b4f2-18b6c3b4e2cd.gif)
顶可以改成这样吗

**Comment by balh55y** [comment]
![0E58034650EA28DF989A568645C035B9](https://user-images.githubusercontent.com/85926883/184506475-b2f6ff12-7d7c-4f92-a7e2-b17eecbf9ccc.jpg)
可以多关键字一起发然后放出最后处理的图片吗,例如 阿尼亚喜欢+胡桃

**Comment by balh55y** [comment]
> ![0E58034650EA28DF989A568645C035B9](https://user-images.githubusercontent.com/85926883/184506475-b2f6ff12-7d7c-4f92-a7e2-b17eecbf9ccc.jpg) 可以多关键字一起发然后放出最后处理的图片吗，比如阿尼亚喜欢+胡桃

先设定一个连接符比如"&",然后拆分字符串再正则匹配关键字循环处理一下
不知可行不可行...

**Comment by MeetWq** [comment]
> 可以多关键字一起发然后放出最后处理的图片吗，比如阿尼亚喜欢+胡桃
> 
> 先设定一个连接符比如"&",然后拆分字符串再正则匹配关键字循环处理一下 不知可行不可行...

感觉不太可行，而且意义不大，建议手动套娃

**Comment by jcjrobert** [comment]
> ![259BCB5B70AB515E031A6D0AA518DB5B](https://user-images.githubusercontent.com/106854600/178235893-1d0545fb-b9dc-44de-9a66-95c7ef8e54c4.jpg) ![7732E685327DC62D0D355599AAA42268](https://user-images.githubusercontent.com/106854600/178236081-fdcbc4a3-f0e2-4f8e-b1c4-f3b6956280b2.jpg) ![6864AD7C0F5B29DC3542F3060B93A2E9](https://user-images.githubusercontent.com/106854600/178236104-54e28134-edde-47e2-bf38-71ddbcfa045d.jpg) ![1F08B4A28CCA43C01F39DD2E898FD4B4](https://user-images.githubusercontent.com/106854600/178236121-fd0bdd75-2eb0-4345-ad0d-35ca638d8f79.jpg) ![2FEA51EAEAF64DD94FB2883A687A86DD](https://user-images.githubusercontent.com/106854600/178236133-41be056f-20b8-4612-ae6c-81b3c0ca1245.jpg) ![BA4BAE75CAEFBDECF2FB11CB5BB832F5](https://user-images.githubusercontent.com/106854600/178236153-582b4724-6ff3-4868-beff-62dfcc4f03f9.jpg) ![BB39F528232BD6ED67B7A814CE694DE3](https://user-images.githubusercontent.com/106854600/178236176-1cebe128-5755-485d-ae1a-fcf26f5f5f5b.jpg) ![5BFA295F1FA7BDE03CD83FA18F7C6AEA](https://user-images.githubusercontent.com/106854600/178236206-1b4fbd12-8dea-4d6e-a954-a917282d09e6.jpg) mq佬考虑加个图片置于头像上加个自定义文字， 双手 自己 让我捏捏你的屁股

打算pr一个这个，但会刷好几个指令，不知道是直接加还是换种形式（指合并）

**Comment by MeetWq** [comment]
> 打算pr一个这个，但会刷好几个指令，不知道是直接加还是换种形式（指合并）

不太理解这是什么，先看看你做的效果吧

**Comment by othinus001** [comment]
![u_182868774_1987186019 fm_253 app_138 f_JPEG](https://user-images.githubusercontent.com/38730318/185449338-576305ce-dc7c-4b1e-bdb7-ee3a933cbcef.jpeg)
![2ea9331fb8d8dec5](https://user-images.githubusercontent.com/38730318/185449333-6f1200f9-0332-4726-8a2a-1bce292e3a72.jpg)
![002](https://user-images.githubusercontent.com/38730318/185449414-cc6b842d-10f4-4cf4-8115-8b3cbadca092.png)

类似这样的，封面和中间文字，或者类似的汤姆猫看书

**Comment by realhuhu** [comment]
![85_X%N}$IZ6HER4{N)R77}U](https://user-images.githubusercontent.com/81463123/185895883-b7ad3422-78c2-46ed-b7e4-f0a5efdb9479.gif)
接头霸王

**Comment by balh55y** [comment]
![51O$~U5IO5D$IZ1_J3)A9W5](https://user-images.githubusercontent.com/85926883/186336568-a1dcfa04-534f-4487-8def-5401469364c0.gif)
这个冒数学公式的滤镜
https://balh5.lanzouy.com/iQsMD0a5198j
只找到绿幕视频

**Comment by balh55y** [comment]
![QQ图片20220824133242](https://user-images.githubusercontent.com/85926883/186336990-d1366b1e-2d64-47ba-9b85-b51922216389.gif)
这个冒数学公式能做吗
只找到了绿幕视频
https://balh5.lanzouy.com/iQsMD0a5198j

**Comment by shmilyty** [comment]
![J 3M~77) BYOAUV(L@2I4%A](https://user-images.githubusercontent.com/61276699/186565298-8508a65d-a458-487d-b8ab-3439c6bfdfb6.jpg)
可以把下面的两个头像分别作为调用该命令的参数

**Comment by KarisAya** [comment]
在想我的事情
![70cfcad7277f9e2f81a007df5a30e924b999f312](https://user-images.githubusercontent.com/51886078/186740429-319b3fa1-8cdc-4280-a805-ae82904cb7f2.jpg)

**Comment by balh55y** [comment]
![KGH~}H1TL8 GUAH@FEQ26~L](https://user-images.githubusercontent.com/85926883/190916119-aaa235db-400b-4585-8079-30899382ba90.jpg)
无响应

**Comment by cj0928** [comment]
大佬，可以加个可达鸭吗？_(´ཀ`」 ∠)_
![image](https://user-images.githubusercontent.com/104024133/190999292-b3301a29-36a2-4f81-a0ea-051090b51117.gif)

**Comment by othinus001** [comment]
> 大佬，可以加个可达鸭吗？_(´ཀ`」 ∠)_ ![image](https://user-images.githubusercontent.com/104024133/190999292-b3301a29-36a2-4f81-a0ea-051090b51117.gif) [ ![image](https://user-images.githubusercontent.com/104024133/190999292-b3301a29-36a2-4f81-a0ea-051090b51117.gif) ](https://user-images.githubusercontent.com/104024133/190999292-b3301a29-36a2-4f81-a0ea-051090b51117.gif) [ ](https://user-images.githubusercontent.com/104024133/190999292-b3301a29-36a2-4f81-a0ea-051090b51117.gif)

你这个去https://github.com/noneplugin/nonebot-plugin-memes

**Comment by balh55y** [comment]
![NAUNH{K40AY)7THJ $KCE N](https://user-images.githubusercontent.com/85926883/193453704-432336d1-3841-41b6-8e92-6730c49f9319.gif)
把图片放平板上,具体叫啥我也没头绪

**Comment by MeetWq** [comment]
欢迎加入QQ群讨论：682145034

**Comment by Jerry-FaGe** [comment]
- 关键词
  敲木鱼/赛博功德

- 表情包原图
  ![U7B LAW8EON(5TCC ) 5RW](https://user-images.githubusercontent.com/40235071/202106758-7561fae1-f3ca-458b-8183-be03242fc1ec.gif)

- 表情包效果图，或者说明在什么地方添加头像
  这个可能扣起来有点难唉，目前我也没什么思路。不过要是做出来岂不是狠狠地恰一波热度（

**Comment by F1Justin** [comment]
关键词: 偷学
模板: 
![偷学](https://user-images.githubusercontent.com/30348215/205445524-baedadd4-5870-4520-a4ee-9d0d7e349677.png)
直接填充透明部分就行,像这样
![偷学代数lang](https://user-images.githubusercontent.com/30348215/205445646-5f1ffbd6-dcb3-4543-a0dc-106d50fb9f9a.png)

**Comment by Jerry-FaGe** [comment]
> * 关键词
>   敲木鱼/赛博功德
> * 表情包原图
>   ![U7B LAW8EON(5TCC ) 5RW](https://user-images.githubusercontent.com/40235071/202106758-7561fae1-f3ca-458b-8183-be03242fc1ec.gif)
> * 表情包效果图，或者说明在什么地方添加头像
>   这个可能扣起来有点难唉，目前我也没什么思路。不过要是做出来岂不是狠狠地恰一波热度（

hhhc 我想的是把头像P狂三头上没想到给P木鱼上了hhhhh不过也挺有意思的

**Comment by realhuhu** [comment]
![image](https://user-images.githubusercontent.com/81463123/208241354-98c1e587-c254-4dae-9084-d346bc39cdba.png)
妈妈生的

**Comment by daseinem** [comment]
- 关键词 离婚协议
- 表情包原图
  
![-7f188831c255f9c3](https://user-images.githubusercontent.com/86276507/210061651-a2c5ff34-27fb-41a7-8695-985984e343f3.jpg)

- 表情包效果 类似结婚申请，背景替换为头像

**Comment by Xiao-yux** [comment]
这个可以加吗？
![image](https://user-images.githubusercontent.com/79674967/216248769-d586b6a3-b2ef-4ad5-86be-e0557ba5c45a.png)
![QQ图片20230202142825](https://user-images.githubusercontent.com/79674967/216248792-38425ffc-a5f1-4491-ba3a-072e0d224fd3.gif)

**Comment by kevin8717** [comment]
![886386BD-8823-4319-8D5B-9BEA5E68738F](https://user-images.githubusercontent.com/26052424/218297735-24dc7e4c-ba00-49f9-85e1-10a7eeff2f7c.gif)
加上这个，把狗替换成群友头像，关键词“哪来的狗”
