### ISSUE TITLE
发送“/头像表情包”生成出来的图片为空，是bug吗？

### ISSUE THREAD

**Issue by LittlebearHat** [noneplugin/nonebot-plugin-petpet#74]
返回列表图片如下：[https://all.czse7cxw.xyz/images/629f354c04c5189441873a89.jpg](url)

**Comment by MeetWq** [comment]
字体问题，看[nonebot-plugin-imageutils](https://github.com/noneplugin/nonebot-plugin-imageutils)字体部分说明

**Comment by LittlebearHat** [comment]
Ubuntu系统字体问题，已解决，谢谢
