### ISSUE TITLE
头像获取错误

### ISSUE THREAD

**Issue by realhuhu** [noneplugin/nonebot-plugin-petpet#81]
根据qq获取头像错误
![image](https://user-images.githubusercontent.com/81463123/173614875-733a3e89-3ba4-4034-9402-d9476d00f586.png)
貌似这个代码的判断没有生效
![image](https://user-images.githubusercontent.com/81463123/173614989-aee21924-887d-4f2b-aa5f-c441e526d259.png)

**Comment by MeetWq** [comment]
他的qq号是多少？我试试

**Comment by realhuhu** [comment]
> 他的qq号是多少？我试试

84307122

**Comment by MeetWq** [comment]
我试了是可以的
![Snipaste_2022-06-15_22-39-28](https://user-images.githubusercontent.com/33149974/173854886-3eb0fa03-9a34-4f84-9329-736bc8f16afe.png)

**Comment by realhuhu** [comment]
> 我试了是可以的 ![Snipaste_2022-06-15_22-39-28](https://user-images.githubusercontent.com/33149974/173854886-3eb0fa03-9a34-4f84-9329-736bc8f16afe.png)

可能我用的api不是最新版，用的是这个https://api.dlut-cc.live/emoji/?flag=_&qq=2661467107&target=84307122&group=460970728&args=%E4%BA%B2%E4%BA%B2&master=2661467107

**Comment by MeetWq** [comment]
那就不是这边的问题了，你去找api的提供者吧
