### ISSUE TITLE
启动时下载资源失败

### ISSUE THREAD

**Issue by whqwq** [noneplugin/nonebot-plugin-petpet#85]
![image](https://user-images.githubusercontent.com/89032947/176888778-18820502-dc8f-46be-acc0-5fe86e4b322f.png)

是jsdelivr的问题？

后来我把resource下的image文件夹复制到data/petpet/下，启动插件的时候还是会去jsdelivr上下载resource_list而报错，我只好把这个函数给部分注释掉了（

**Comment by MeetWq** [comment]
jsdelivr 时不时抽风
每次启动会检查更新，如果手动下载了图片是可以正常使用的，报错不影响

**Comment by MeetWq** [comment]
jsdelivr好像有些问题，我之后还是换成fastgit吧

**Comment by whqwq** [comment]
好的好的，谢谢大佬
