### ISSUE TITLE
新人求助

### ISSUE THREAD

**Issue by YEYISHENG** [noneplugin/nonebot-plugin-petpet#86]
作者大大好！我是一名刚接触Github的新人，在调试您的代码时遇到了如下问题，请问该如何解决
<img width="318" alt="image" src="https://user-images.githubusercontent.com/74827380/177675344-b1cf5a89-1ce0-47bb-9ddb-6e717703b4c6.png">

**Comment by MeetWq** [comment]
建议先学学python
