### ISSUE TITLE
cdn又抽风了

### ISSUE THREAD

**Issue by THNEden** [noneplugin/nonebot-plugin-petpet#92]
![}VCE@KN3TM`1C_AU805Q%ZK](https://user-images.githubusercontent.com/87106832/180017601-ddd58acf-67e7-471b-a83d-c9d739d0b5f5.png)
fastly也跟着抽了，网页能访问进去，图片下载不下来，这样的问题能通过修改cdn解决不，第一次操作bot插件，还请多多指教

**Comment by MeetWq** [comment]
换成 ghproxy 了
