### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by Xiao-yux** [noneplugin/nonebot-plugin-petpet#93]
![image](https://user-images.githubusercontent.com/79674967/180106757-2c3ca855-2d65-4d31-b784-383ed08189a3.png)
新版本是不是把回复图片的操作删除了？上面那个操作用不成了，之前的版本还可以的

**Comment by Xiao-yux** [comment]
现在只能复制粘贴图片使用功能
![image](https://user-images.githubusercontent.com/79674967/180106953-5ba1f7d4-15d0-4901-a032-d338231a1ec6.png)

**Comment by MeetWq** [comment]
回复图片时如果回复的不是机器人，需要把前面的@删掉
