### ISSUE TITLE
能不能增加一个禁止/启用某个表情的功能

### ISSUE THREAD

**Issue by qjksxy** [noneplugin/nonebot-plugin-petpet#94]
比如说我想关闭对称这个表情包

**Comment by jcjrobert** [comment]
对称这个功能是太阴间了么，虽然是我pr的（（（

**Comment by qjksxy** [comment]
@jcjrobert 哈哈哈哈 不是  是这个太好玩了  以至于群里的小伙伴们总是制作这个表情包  导致了严重的刷屏  所以有点想把它关掉了

**Comment by MeetWq** [comment]
新版加了，来点小白鼠试试有无bug（

**Comment by jcjrobert** [comment]
> 新版加了，来点小白鼠试试有无bug（

实装了，全测试了一遍，目前没有bug，mq佬tql

**Comment by qjksxy** [comment]
好耶
