### ISSUE TITLE
想问一下怎么编辑修改用来触发的指令

### ISSUE THREAD

**Issue by Frocean** [noneplugin/nonebot-plugin-petpet#95]
在网上查没搞懂怎么修改源码qwq（其实是找不到地方）
主要是有些指令感觉有点长，想缩减一下..这样

**Comment by MeetWq** [comment]
在 `data_source.py` 里改

**Comment by Frocean** [comment]
> 在 `data_source.py` 里改

找到了！蟹蟹！！
