### ISSUE TITLE
无法显示中文

### ISSUE THREAD

**Issue by 0ceanCat** [noneplugin/nonebot-plugin-petpet#96]
所有中文字符全变成了方块，比如 /问问 自己， 图中的所有中文皆变成了方块。请各位指教，谢谢

**Comment by jcjrobert** [comment]
插件使用 [nonebot-plugin-imageutils](https://github.com/noneplugin/nonebot-plugin-imageutils) 插件来绘制文字，字体配置可参考该插件的说明

**Comment by 0ceanCat** [comment]
谢谢
